package edu.icet.demo.controller;

import edu.icet.demo.service.ProductService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

@RestController
@RequestMapping("/products")
@Slf4j // boilerplate code are generated by project lombok
public class ProductController {

    @Autowired // dependency injection / Field Injection
    @Lazy
    ProductService productServiceOne; //dependency

    @Autowired
    @Lazy
    ProductService productServiceTwo;

    ProductController(){
        log.info("ProductController Object Loaded.");
    }

    //constructor Injection
//    ProductController(ProductService productService){
//        this.productService= productService;
//    }

    //Rest API
    //http://localhost:8080/products/all
    //Method : GET

    @GetMapping("/all/{transactionAmount}")
    Map<String, String> getStudents(@PathVariable String transactionAmount){

        //System.out.println(transactionAmount);
        log.info("Transaction Received. Payment Amount {}",transactionAmount);
        return productServiceOne.getStudents();

    }



}
