import java.util.*;
class Example{
public static void main(String args[]){
Scanner input=new Scanner(System.in);
int c,e,f,h,i,k,l,n;
String a,b;
double d,t1,g,t2,j,t3,m,t4,total;
System.out.println("                \r\n   _____                      _     ______        _     _             \r\n  / ____|                    | |   |  ____|      | |   (_)            \r\n | (___  _ __ ___   __ _ _ __| |_  | |__ __ _ ___| |__  _  ___  _ __  \r\n  \\___ \\| \'_ ` _ \\ / _` | \'__| __| |  __/ _` / __| \'_ \\| |/ _ \\| \'_ \\ \r\n  ____) | | | | | | (_| | |  | |_  | | | (_| \\__ \\ | | | | (_) | | | |\r\n |_____/|_| |_| |_|\\__,_|_|   \\__| |_|  \\__,_|___/_| |_|_|\\___/|_| |_|\r\n                                                                      \r\n                                                                      \r\n");
System.out.print("Date : ");
a=input.nextLine();
System.out.print("Customer Name : ");
b=input.nextLine();
System.out.println("_____________________________________________________________________");
System.out.println("                            ");
System.out.println("\r\n  _____    ___ _    _     _      \r\n |_   _|__/ __| |_ (_)_ _| |_ ___\r\n   | ||___\\__ \\ \' \\| | \'_|  _(_-<\r\n   |_|    |___/_||_|_|_|  \\__/__/\r\n                                 \r\n");
System.out.print("Number of T-Shirts : ");
c=input.nextInt();
System.out.print("Unit price of T-Shirt : ");
d=input.nextDouble();
System.out.print("Discount Rate (%) : ");
e=input.nextInt();
t1=d*c*(100-e)/100.0;
System.out.println("                            ");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Description          |      QTY       |    Unit Price     |         Amount      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| T-Shirt              |     "+c+"          |     "+d+"         |         "+t1+"      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("                          ");
System.out.println("_____________________________________________________________________");
System.out.println("\r\n  _____                            \r\n |_   _| _ ___ _  _ ___ ___ _ _ ___\r\n   | || \'_/ _ \\ || (_-</ -_) \'_(_-<\r\n   |_||_| \\___/\\_,_/__/\\___|_| /__/\r\n                                   \r\n");
System.out.print("Number of Trousers : ");
f=input.nextInt();
System.out.print("Unit Price of Trouser : ");
g=input.nextDouble();
System.out.print("Discount Rate (%) : ");
h=input.nextInt();
t2=f*g*(100-h)/100.0;
System.out.println("                            ");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Description          |      QTY       |    Unit Price     |         Amount      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("|Trouser               |     "+f+"          |     "+g+"        |         "+t2+"      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("                          ");
System.out.println("_____________________________________________________________________");
System.out.println("\r\n  ___ _    _     _      \r\n / __| |_ (_)_ _| |_ ___\r\n \\__ \\ \' \\| | \'_|  _(_-<\r\n |___/_||_|_|_|  \\__/__/\r\n                        \r\n");
System.out.print("Number of Shirts : ");
i=input.nextInt();
System.out.print("Unit Price of Shirt : ");
j=input.nextDouble();
System.out.print("Discount Rate (%) : ");
k=input.nextInt();
t3=i*j*(100-k)/100.0;
System.out.println("                            ");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Description          |      QTY       |    Unit Price     |         Amount      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Shirt                |     "+i+"          |     "+j+"        |         "+t3+"      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("                          ");
System.out.println("_____________________________________________________________________");
System.out.println("\r\n  ___ _            _      \r\n / __| |_  ___ _ _| |_ ___\r\n \\__ \\ \' \\/ _ \\ \'_|  _(_-<\r\n |___/_||_\\___/_|  \\__/__/\r\n                          \r\n");
System.out.print("Number of Shorts : ");
l=input.nextInt();
System.out.print("Unit Price of Short : ");
m=input.nextDouble();
System.out.print("Discount Rate (%) : ");
n=input.nextInt();
t4=l*m*(100-n)/100.0;
System.out.println("                            ");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Description          |      QTY       |    Unit Price     |         Amount      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Short                |     "+l+"          |     "+m+"         |         "+t4+"      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("                          ");
System.out.println("__________________________________________________________________________________");
System.out.println("                                        ");
total=t1+t2+t3+t4;
System.out.println("+---------------------------------------------------------------------------------+");
System.out.println("|                    ___ _ _ _   ___                                              |");
System.out.println("|                   | _ |_) | | / __|_  _ _ __  _ __  __ _ _ _ _  _               |");
System.out.println("|                   | _ \\ | | | \\__ \\ || | '  \\| '  \\/ _` | '_| || |              |");
System.out.println("|                   |___/_|_|_| |___/\\_,_|_|_|_|_|_|_\\__,_|_|  \\_, |              |");
System.out.println("|                                                              |__/               |");
System.out.println("| Customer : "+b+"                                           Date : "+a+"  |");
System.out.println("|                                                                                 |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Description          |      QTY       |    Unit Price     |         Amount      |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("|                      |                |                   |                     |");
System.out.println("| T-Shirt              |     "+c+"          |     "+d+"         |         "+t1+"      |");
System.out.println("|                      |                |                   |                     |");
System.out.println("| Trouser              |     "+f+"          |     "+g+"        |         "+t2+"      |");
System.out.println("|                      |                |                   |                     |");
System.out.println("| Shirt                |     "+i+"          |     "+j+"        |         "+t3+"      |");
System.out.println("|                      |                |                   |                     |");
System.out.println("| Short                |     "+l+"          |     "+m+"         |         "+t4+"      |");
System.out.println("|                      |                |                   |                     |");
System.out.println("+----------------------+----------------+-------------------+---------------------+");
System.out.println("| Total                                                     |         "+total+"      |");
System.out.println("+-----------------------------------------------------------+---------------------+");
}
}